### ISSUE TITLE
Help: Installing OpenWrt on Phicomm K2

### ISSUE THREAD

**Issue by faahim** [RC1844/Actions-OpenWrt-Phicomm-K2#1]
Hi there!

I came across this repo while looking for a way to install OpenWrt on the Phicomm K2.

I have got this router from China and the built-in firmware seems to be a modified and restricted version of OpenWrt (I'm attaching a screenshot in case that helps).
![image](https://user-images.githubusercontent.com/21854687/149346401-7dc1fa40-0ce3-41df-bcef-88e3bc22fc55.png)

It's completely in Chinese and doesn't have an option to reset/replace the firmware. I can't access it through SSH either. I've been looking around for ways to flash the official OpenWrt on it without much luck.

Could please help me or point me to any resource that might be useful?
Thanks!

**Comment by RC1844** [comment]
You can use the browser's translation to find the correct options

**Comment by faahim** [comment]
Hi!

Thanks for responding!

Translating is not the issue. I'd just like to have the official firmware installed. I need to run it in "Realy" mode, which isn't working with this current setup for some reason.

This repo looks like a custom OpenWrt build for this router? Do you use it on your K2? Is there any instruction I could follow to get it installed on mine?

Thanks!

**Comment by RC1844** [comment]
If you want an English only system, you can delete the following

CONFIG_LUCI_LANG_zh-cn=y

**Comment by RC1844** [comment]
> Hi!
> 
> Thanks for responding!
> 
> Translating is not the issue. I'd just like to have the official firmware installed. I need to run it in "Realy" mode, which isn't working with this current setup for some reason.
> 
> This repo looks like a custom OpenWrt build for this router? Do you use it on your K2? Is there any instruction I could follow to get it installed on mine?
> 
> Thanks!

OK, this is not the official firmware. You should download it on the official website

**Comment by faahim** [comment]
Thanks again!

My main problem is that I don't know how to install this (of the official) firmware on the router. That is what I need help with.

**Comment by RC1844** [comment]
> Thanks again!
> 
> My main problem is that I don't know how to install this (of the official) firmware on the router. That is what I need help with.

I use the "breed" to install.You can try searching, usually Chinese tutorials
